[features]
seeds = false
skip-lint = false
[programs.localnet]
create_account = "82qMKny4FNb1ZXiwD9xQEXEV7bjEeUCZcrmjMMizho1M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
